module.exports = {
  ADMIN: 'ADMIN',
  DONOR: 'DONOR',
  BLOOD_CAMP: 'BLOOD_CAMP',
  BLOOD_TEST_CENTER: 'BLOOD_TEST_CENTER',
  BLOOD_SEPARATION_CENTER: 'BLOOD_SEPARATION_CENTER',
  BLOOD_BANK: 'BLOOD_BANK',
  HOSPITAL: 'HOSPITAL',
};
